saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.OrderListView.as_view(), name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$', views.orderline_change_quantity,
        name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$', views.orderline_split,
        name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$', views.ship_delivery_group,
        name='ship-delivery-group')
]

saleor/order/urls.py
from django.conf.urls import patterns, url

from ..core import TOKEN_PATTERN
from . import views


urlpatterns = [
    url(r'^%s/$' % (TOKEN_PATTERN,), views.details, name='details'),
    url(r'^%s/payment/$' % (TOKEN_PATTERN,),
        views.payment, name='payment'),
    url(r'^%s/payment/(?P<variant>[-\w]+)/$' % (TOKEN_PATTERN,),
        views.start_payment, name='payment'),
    url(r'^%s/cancel-payment/$' % (TOKEN_PATTERN,), views.cancel_payment,
        name='cancel-payment')
]

saleor/registration/urls.py
from django.conf.urls import patterns, url

from ..core import TOKEN_PATTERN
from . import views


urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^oauth_callback/(?P<service>\w+)/$', views.oauth_callback,
        name='oauth_callback'),
    url(r'^change_password/$', views.change_password,
        name='change_password'),
    url(r'^request_email_confirmation/$', views.request_email_confirmation,
        name='request_email_confirmation'),
    url(r'^confirm_email/%s/$' % (TOKEN_PATTERN,), views.confirm_email,
        name='confirm_email'),
    url(r'^request_email_change/$', views.request_email_change,
        name='request_email_change'),
    url(r'^change_email/%s/$' % (TOKEN_PATTERN,), views.change_email,
        name='change_email')
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap


from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .dashboard.urls import urlpatterns as dashboard_urls


admin.autodiscover()

urlpatterns = [
    url(r'^$', include(core_urls), name='home'),
    url(r'^account/', include(registration_urls, namespace='registration')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^ccavenue/', include('dcavenue.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT})]

saleor/userprofile/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.details, name='details'),
    url(r'^orders/$', views.orders, name='orders'),
    url(r'^address/create/$', views.address_create,
        name='address-create'),
    url(r'^address/(?P<pk>\d+)/edit/$', views.address_edit,
        name='address-edit'),
    url(r'^address/(?P<pk>\d+)/delete/$',
        views.address_delete, name='address-delete'),
    url(r'^address/(?P<pk>\d+)/make-default-for-'
        r'(?P<purpose>billing|shipping)/$', views.address_make_default,
        name='address-make-default')
]

saleor/dashboard/order/views.py
from __future__ import unicode_literals

from django.contrib import messages
from django.core.context_processors import csrf
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView
from django_prices.templatetags.prices_i18n import gross
from prices import Price

from ...order.models import Order, OrderedItem, OrderNote
from ...userprofile.forms import AddressForm
from ..views import (StaffMemberOnlyMixin, FilterByStatusMixin,
                     staff_member_required)
from .forms import (OrderNoteForm, MoveItemsForm,
                    ChangeQuantityForm, ShipGroupForm, CapturePaymentForm,
                    ReleasePaymentForm, RefundPaymentForm)
from ...product.models.base import ProductVariant


class OrderListView(StaffMemberOnlyMixin, FilterByStatusMixin, ListView):
    template_name = 'dashboard/order/list.html'
    paginate_by = 20
    model = Order

    def get_queryset(self):
        qs = super(OrderListView, self).get_queryset()
        return qs.prefetch_related(
            'groups', 'payments', 'groups__items').select_related('user')


@staff_member_required
def order_details(request, order_pk):
    qs = (Order.objects
          .select_related('user', 'shipping_address', 'billing_address')
          .prefetch_related('notes', 'payments', 'history',
                            'groups', 'groups__items'))
    order = get_object_or_404(qs, pk=order_pk)
    notes = order.notes.all()
    all_payments = order.payments.all()
    payment = order.payments.last()
    groups = list(order)
    captured = preauthorized = Price(0, currency=order.get_total().currency)
    if payment:
        can_capture = (payment.status == 'preauth' and
                       order.status != 'cancelled')
        can_release = payment.status == 'preauth'
        can_refund = payment.status == 'confirmed'
        preauthorized = payment.get_total_price()
        if payment.status == 'confirmed':
            captured = payment.get_captured_price()
    else:
        can_capture = can_release = can_refund = False

    ctx = {'order': order, 'all_payments': all_payments, 'payment': payment,
           'notes': notes, 'groups': groups, 'captured': captured,
           'preauthorized': preauthorized, 'can_capture': can_capture,
           'can_release': can_release, 'can_refund': can_refund}
    return TemplateResponse(request, 'dashboard/order/detail.html', ctx)


@staff_member_required
def order_add_note(request, order_pk):
    order = get_object_or_404(Order, pk=order_pk)
    note = OrderNote(order=order, user=request.user)
    form = OrderNoteForm(request.POST or None, instance=note)
    status = 200
    if form.is_valid():
        form.save()
        msg = _('Added note')
        order.create_history_entry(comment=msg, user=request.user)
        messages.success(request, msg)
    elif form.errors:
        status = 400
    ctx = {'order': order, 'form': form}
    ctx.update(csrf(request))
    template = 'dashboard/order/modal_add_note.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def capture_payment(request, order_pk, payment_pk):
    order = get_object_or_404(Order, pk=order_pk)
    payment = get_object_or_404(order.payments, pk=payment_pk)
    amount = order.get_total().quantize('0.01').gross
    form = CapturePaymentForm(request.POST or None, payment=payment,
                              initial={'amount': amount})
    if form.is_valid() and form.capture():
        amount = form.cleaned_data['amount']
        msg = _('Captured %(amount)s') % {'amount': gross(amount)}
        payment.order.create_history_entry(comment=msg, user=request.user)
        messages.success(request, msg)
        return redirect('dashboard:order-details', order_pk=order.pk)
    status = 400 if form.errors else 200
    ctx = {'captured': payment.captured_amount, 'currency': payment.currency,
           'form': form, 'order': order, 'payment': payment}
    return TemplateResponse(request, 'dashboard/order/modal_capture.html', ctx,
                            status=status)


@staff_member_required
def refund_payment(request, order_pk, payment_pk):
    order = get_object_or_404(Order, pk=order_pk)
    payment = get_object_or_404(order.payments, pk=payment_pk)
    amount = payment.captured_amount
    form = RefundPaymentForm(request.POST or None, payment=payment,
                             initial={'amount': amount})
    if form.is_valid() and form.refund():
        amount = form.cleaned_data['amount']
        msg = _('Refunded %(amount)s') % {'amount': gross(amount)}
        payment.order.create_history_entry(comment=msg, user=request.user)
        messages.success(request, msg)
        return redirect('dashboard:order-details', order_pk=order.pk)
    status = 400 if form.errors else 200
    ctx = {'captured': payment.captured_amount, 'currency': payment.currency,
           'form': form, 'order': order, 'payment': payment}
    return TemplateResponse(request, 'dashboard/order/modal_refund.html', ctx,
                            status=status)


@staff_member_required
def release_payment(request, order_pk, payment_pk):
    order = get_object_or_404(Order, pk=order_pk)
    payment = get_object_or_404(order.payments, pk=payment_pk)
    form = ReleasePaymentForm(request.POST or None, payment=payment)
    if form.is_valid() and form.release():
        msg = _('Released payment')
        payment.order.create_history_entry(comment=msg, user=request.user)
        messages.success(request, msg)
        return redirect('dashboard:order-details', order_pk=order.pk)
    status = 400 if form.errors else 200
    ctx = {'captured': payment.captured_amount, 'currency': payment.currency,
           'form': form, 'order': order, 'payment': payment}
    return TemplateResponse(request, 'dashboard/order/modal_release.html', ctx,
                            status=status)


@staff_member_required
def orderline_change_quantity(request, order_pk, line_pk):
    order = get_object_or_404(Order, pk=order_pk)
    item = get_object_or_404(OrderedItem.objects.filter(
        delivery_group__order=order), pk=line_pk)
    form = ChangeQuantityForm(request.POST or None, instance=item)
    status = 200
    old_quantity = item.quantity
    if form.is_valid():
        with transaction.atomic():
            form.save()
        msg = _(
            'Changed quantity for product %(product)s from'
            ' %(old_quantity)s to %(new_quantity)s') % {
                'product': item.product, 'old_quantity': old_quantity,
                'new_quantity': item.quantity}
        order.create_history_entry(comment=msg, user=request.user)
        messages.success(request, msg)
    elif form.errors:
        status = 400
    ctx = {'order': order, 'object': item, 'form': form}
    template = 'dashboard/order/modal_change_quantity.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def orderline_split(request, order_pk, line_pk):
    order = get_object_or_404(Order, pk=order_pk)
    item = get_object_or_404(OrderedItem.objects.filter(
        delivery_group__order=order), pk=line_pk)
    form = MoveItemsForm(request.POST or None, item=item)
    line_pk = None
    if item:
        line_pk = item.pk
    status = 200
    if form.is_valid():
        old_group = item.delivery_group
        how_many = form.cleaned_data['quantity']
        with transaction.atomic():
            target_group = form.move_items()
        if not old_group.pk:
            old_group = _('removed group')
        msg = _(
            'Moved %(how_many)s items %(item)s from %(old_group)s'
            ' to %(new_group)s') % {
                'how_many': how_many, 'item': item, 'old_group': old_group,
                'new_group': target_group}
        order.create_history_entry(comment=msg, user=request.user)
        messages.success(request, msg)
    elif form.errors:
        status = 400
    ctx = {'order': order, 'object': item, 'form': form, 'line_pk': line_pk}
    template = 'dashboard/order/modal_split_order_line.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def ship_delivery_group(request, order_pk, group_pk):
    order = get_object_or_404(Order, pk=order_pk)
    group = get_object_or_404(order.groups.all(), pk=group_pk)
    form = ShipGroupForm(request.POST or None, instance=group)
    status = 200
    if form.is_valid():
        with transaction.atomic():
            form.save()
            for _ord in order.get_items():
                pv = ProductVariant.objects.get(product=_ord.product)
                for _stk in pv.stock.all():
                    if _stk.quantity > 0:
                        if _stk.quantity > _ord.quantity:
                            _stk.quantity -= _ord.quantity
                            _stk.save()
        msg = _('Shipped %s') % group
        messages.success(request, msg)
        group.order.create_history_entry(comment=msg, user=request.user)
        return redirect('dashboard:order-details', order_pk=order_pk)
    elif form.errors:
        status = 400
    ctx = {'order': order, 'group': group}
    template = 'dashboard/order/modal_ship_delivery_group.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def address_view(request, order_pk, address_type):
    order = Order.objects.get(pk=order_pk)
    if address_type == 'shipping':
        address = order.shipping_address
        success_msg = _('Updated shipping address')
    else:
        address = order.billing_address
        success_msg = _('Updated billing address')
    form = AddressForm(request.POST or None, instance=address)
    status = 200
    if form.is_valid():
        form.save()

saleor/userprofile/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.views.decorators.http import require_POST
from django.utils.translation import ugettext as _

from .forms import AddressForm


@login_required
def details(request):
    ctx = {'addresses': request.user.addresses.all()}
    return TemplateResponse(request, 'userprofile/details.html', ctx)


@login_required
def orders(request):

    ctx = {'orders': request.user.orders.prefetch_related('groups')}
    return TemplateResponse(request, 'userprofile/orders.html', ctx)


@login_required
def address_edit(request, pk):
    address = get_object_or_404(request.user.addresses, pk=pk)
    address_form = AddressForm(request.POST or None, instance=address)
    if address_form.is_valid():
        address_form.save()
        message = _('Address successfully updated.')
        messages.success(request, message)
        return HttpResponseRedirect(reverse('profile:details'))
    return TemplateResponse(
        request, 'userprofile/address-edit.html',
        {'address_form': address_form})


@login_required
def address_create(request):
    user = request.user
    address_form = AddressForm(request.POST or None)
    if address_form.is_valid():
        address = address_form.save()
        user.addresses.add(address)
        user.default_shipping_address = address
        user.default_billing_address = address
        user.save(update_fields=[
            'default_shipping_address', 'default_billing_address'])
        message = _('Address successfully created.')
        messages.success(request, message)
        return HttpResponseRedirect(reverse('profile:details'))
    return TemplateResponse(
        request, 'userprofile/address-edit.html',
        {'address_form': address_form})


@login_required
def address_delete(request, pk):
    address = get_object_or_404(request.user.addresses, pk=pk)
    if request.method == 'POST':
        address.delete()
        messages.success(request, _('Address successfully deleted.'))
        return HttpResponseRedirect(reverse('profile:details'))
    return TemplateResponse(
        request, 'userprofile/address-delete.html', {'address': address})


@login_required
@require_POST
def address_make_default(request, pk, purpose):
    user = request.user
    address = get_object_or_404(user.addresses, pk=pk)
    if purpose == 'shipping':
        user.default_shipping_address = address
        user.save(update_fields=['default_shipping_address'])
    elif purpose == 'billing':
        user.default_billing_address = address
        user.save(update_fields=['default_billing_address'])
    else:
        raise Http404('Unknown purpose')
    return redirect('profile:details')

saleor/userprofile/templates/userprofile/address-delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Delete address" %} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'profile:details' %}">{% trans "Your profile" %}</a></li>
    <li><a href=".">{% trans "Delete address" %}</a></li>
{% endblock breadcrumb %}

{% block content %}
    <h2>{% trans "Are you sure you want to delete the following address?" %}</h2>

    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ address }}
                </div>
                <div class="panel-body">
                    <address>{% include "userprofile/snippets/address-details.html" with address=address %}</address>
                </div>
            </div>
        </div>
    </div>

    <form action="." method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
        <a href="{% url 'profile:details' %}" class="btn btn-link">{% trans "Cancel" %}</a>
    </form>
{% endblock content %}

saleor/userprofile/templates/userprofile/address-edit.html
{% extends "base.html" %}

{% load as_vertical_form from bootstrap %}
{% load i18n %}

{% block title %}{% trans "Edit Address" %} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'profile:details' %}">{% trans "Your profile" %}</a></li>
{% if address_form.instance.pk %}
    <li><a href=".">{% trans "Edit address" %}</a></li>
{% else %}
    <li><a href=".">{% trans "New address" %}</a></li>
{% endif %}
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <form action="." method="post">
                    {% csrf_token %}
                    <fieldset>
                        <legend>{% trans "Address" %}</legend>
                        {{ address_form|as_vertical_form }}
                    </fieldset>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{% url 'profile:details' %}" class="btn btn-link">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

saleor/userprofile/templates/userprofile/details.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Your profile" %} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'profile:details' %}">{% trans "Your profile" %}</a></li>
{% endblock breadcrumb %}

{% block content %}
    <h2>{% trans "Profile" %}</h2>
    <p>
        <a href="{% url 'registration:change_password' %}" class="btn btn-default">{% trans 'Change your password' %}</a>
        <a href="{% url 'registration:request_email_change' %}" class="btn btn-default">{% trans 'Change your email address' %}</a>
    </p>


    <h3>{% trans "Your address book" %}</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-sm-2">{% trans "Short alias" %}</th>
                <th class="col-sm-4">{% trans "Addressee" %}</th>
                <th class="col-sm-2">{% trans "Billing" %}</th>
                <th class="col-sm-2">{% trans "Shipping" %}</th>
                <th class="col-sm-2"></th>
            </tr>
        </thead>
        <tbody>
            {% for address in addresses %}
            <tr>
                <th class="col-sm-2">
                    {{ address }}
                </th>
                <td class="col-sm-4">
                    {{ address }}
                </td>
                <td class="col-sm-2">
                    {% if user.default_billing_address == address %}
                    <span class="label label-default">{% trans "Default" %}</span>
                    {% else %}
                    <form method="post" action="{% url "profile:address-make-default" pk=address.pk purpose="billing" %}" class="form-inline form-horizontal">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default btn-sm">{% trans "Make default" %}</button>
                    </form>
                    {% endif %}
                </td>
                <td class="col-sm-2">
                    {% if user.default_shipping_address == address %}
                    <span class="label label-default">{% trans "Default" %}</span>
                    {% else %}
                    <form method="post" action="{% url "profile:address-make-default" pk=address.pk purpose="shipping" %}" class="form-inline form-horizontal">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default btn-sm">{% trans "Make default" %}</button>
                    </form>
                    {% endif %}
                </td>
                <td class="col-sm-2">
                    <a href="{% url 'profile:address-edit' pk=address.pk %}" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-edit"></i> {% trans "Edit" %}</a>
                    <a href="{% url 'profile:address-delete' pk=address.pk %}" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-remove"></i> {% trans "Delete" %}</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div>
        <a href="{% url 'profile:address-create' %}" class="btn btn-default"><i class="glyphicon glyphicon-plus-sign"></i> {% trans "Add new address" %}</a>
    </div>


{% endblock content %}

saleor/userprofile/templates/userprofile/orders.html
{% extends "base.html" %}
{% load i18n %}
{% load gross from prices_i18n %}

{% block title %}{% trans "Your orders" %} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'profile:orders' %}">{% trans "Your orders" %}</a></li>
{% endblock breadcrumb %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-sm-2">
                    {% trans "Order #" %}
                </th>
                <th class="col-sm-2">
                    {% trans "Date" %}
                </th>
                <th class="col-sm-2">
                    {% trans "Price" %}
                </th>
                <th class="col-sm-2">
                    {% trans "Status" %}
                </th>
                <th class="col-sm-2">
                    {% trans "Last status change" %}
                </th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td class="col-sm-2">
                        <a href="{{ order.get_absolute_url }}">{{ order }}</a>
                    </td>
                    <td class="col-sm-2">
                        {{ order.created }}
                    </td>
                    <td class="col-sm-2">
                        {% gross order.get_total %}
                    </td>
                    <td class="col-sm-2">
                        <span class="label label-default">{{ order.get_status_display }}</span>
                    </td>
                    <td class="col-sm-2">
                        {{ order.last_status_change }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}