saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.OrderListView.as_view(), name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$', views.orderline_change_quantity,
        name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$', views.orderline_split,
        name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$', views.ship_delivery_group,
        name='ship-delivery-group')
]

saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import api
from . import views


urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^add/$',
        views.product_create, name='product-add'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_edit, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/bulk_delete/',
        views.variants_bulk_delete, name='variant-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/$',
        views.stock_edit, name='product-stock-update'),
    url(r'^(?P<product_pk>[0-9]+)/stock/add/$',
        views.stock_edit, name='product-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/delete/$',
        views.stock_delete, name='product-stock-delete'),
    url(r'^(?P<product_pk>[0-9]+)/stock/bulk_delete/',
        views.stock_bulk_delete, name='stock-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_edit, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),
    url('^(?P<product_pk>[0-9]+)/images/reorder/$',
        api.reorder_product_images, name='product-images-reorder'),
    url('^(?P<product_pk>[0-9]+)/images/upload/$',
        api.upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='product-attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_edit, name='product-attribute-update'),
    url(r'attributes/add/$',
        views.attribute_edit, name='product-attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='product-attribute-delete'),
]

saleor/dashboard/urls.py
from django.conf.urls import url, include

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .customer.urls import urlpatterns as customer_urls
from .order.urls import urlpatterns as order_urls
from .payments.urls import urlpatterns as payments_urls
from .product.urls import urlpatterns as product_urls


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^payments/', include(payments_urls)),
    url(r'^customers/', include(customer_urls)),
]

saleor/product/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
    url(r'^category/(?P<path>[a-z0-9-_/]+?)-(?P<category_id>[0-9]+)/$',
        views.category_index, name='category')
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap


from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .dashboard.urls import urlpatterns as dashboard_urls


admin.autodiscover()

urlpatterns = [
    url(r'^$', include(core_urls), name='home'),
    url(r'^account/', include(registration_urls, namespace='registration')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^ccavenue/', include('dcavenue.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT})]

saleor/dashboard/category/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import ugettext_lazy as _

from ...product.models import Category
from ..views import staff_member_required
from .forms import CategoryForm


@staff_member_required
def category_list(request, root_pk=None):
    root = None
    path = None
    categories = Category.tree.root_nodes()
    if root_pk:
        try:
            root = get_object_or_404(Category, pk=root_pk)
            path = root.get_ancestors(include_self=True) if root else []
            categories = root.get_children()
        except:
            pass
    ctx = {'categories': categories, 'path': path, 'root': root}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
def category_create(request, root_pk=None):
    category = Category()
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(request, _('Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
def category_edit(request, root_pk=None):
    category = get_object_or_404(Category, pk=root_pk)
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(request, _('Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status}
    template = 'dashboard/category/modal_edit.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(request, _('Deleted category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            print 'RP -> ,', root_pk
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            print 'ELSE'
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(request,
                            'dashboard/category/modal_category_confirm_delete.html',
                            ctx)

saleor/dashboard/customer/views.py
from __future__ import unicode_literals

from django.db.models import Count, Max
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.utils.translation import ugettext_lazy as _

from .forms import CustomerSearchForm
from ..utils import paginate
from ..views import staff_member_required
from ...userprofile.models import User


@staff_member_required
def customer_list(request):
    customers = (
        User.objects
        .prefetch_related('orders', 'addresses')
        .select_related('default_billing_address', 'default_shipping_address')
        .annotate(
            num_orders=Count('orders', distinct=True),
            last_order=Max('orders', distinct=True)))

    form = CustomerSearchForm(request.GET or None, queryset=customers)
    form_values = [(field.name, field.value() or '') for field in form]
    if form.is_valid():
        customers = form.search()
    else:
        customers = customers.filter(
            orders__status__in=['new', 'payment-pending', 'fully-paid'])
    title = _('Results (%s)') % len(customers)

    customers, paginator = paginate(customers, 30, request.GET.get('page'))
    ctx = {'customers': customers, 'form': form, 'title': title,
           'paginator': paginator, 'default_pagination_params': form_values}
    return TemplateResponse(request, 'dashboard/customer/list.html', ctx)


@staff_member_required
def customer_details(request, pk):
    queryset = User.objects.prefetch_related(
        'orders', 'addresses').select_related('default_billing_address')
    customer = get_object_or_404(queryset, pk=pk)
    customer_orders = customer.orders.all()
    ctx = {'customer': customer, 'customer_orders': customer_orders}
    return TemplateResponse(request, 'dashboard/customer/detail.html', ctx)

saleor/dashboard/payments/views.py
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.views.generic import ListView
from payments.models import PAYMENT_STATUS_CHOICES

from ..views import (FilterByStatusMixin, StaffMemberOnlyMixin,
                     staff_member_required)
from ...order.models import Payment


class PaymentList(StaffMemberOnlyMixin, FilterByStatusMixin, ListView):
    model = Payment
    template_name = 'dashboard/payments/list.html'
    context_object_name = 'payments'
    paginate_by = 30
    status_choices = PAYMENT_STATUS_CHOICES
    status_order = ['waiting', 'input', 'preauth', 'confirmed', 'refunded',
                    'rejected', 'error']

    def get_queryset(self):
        qs = super(PaymentList, self).get_queryset()
        return qs.order_by('-created').select_related('order')


@staff_member_required
def payment_details(request, pk):
    payment = get_object_or_404(Payment, pk=pk)
    return TemplateResponse(request, 'dashboard/payments/detail.html',
                            {'payment': payment})

saleor/dashboard/views.py
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required \
    as _staff_member_required
from django.db.models import Q, Sum
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormMixin

from ..order.models import Order, Payment
from ..product.models import Product
from saleor.dashboard.order.forms import OrderFilterForm


def staff_member_required(f):
    return _staff_member_required(f, login_url='registration:login')


class StaffMemberOnlyMixin(object):
    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(StaffMemberOnlyMixin, self).dispatch(*args, **kwargs)


class FilterByStatusMixin(FormMixin):
    form_class = OrderFilterForm

    def __init__(self):
        super(FilterByStatusMixin, self).__init__()
        self.active_filter = None

    def get_queryset(self):
        queryset = super(FilterByStatusMixin, self).get_queryset()
        active_filter = self.request.GET.get('status')
        if active_filter:
            self.active_filter = active_filter
            queryset = queryset.filter(status=self.active_filter)
        return queryset

    def get_initial(self):
        initial = super(FilterByStatusMixin, self).get_initial()
        if self.active_filter:
            initial['status'] = self.active_filter
        return initial

    def get_context_data(self):
        ctx = super(FilterByStatusMixin, self).get_context_data()
        ctx['form'] = self.get_form()
        return ctx


@staff_member_required
def index(request):
    orders_to_ship = Order.objects.filter(status='fully-paid')
    orders_to_ship = (orders_to_ship
                      .select_related('user')
                      .prefetch_related('groups', 'groups__items', 'payments'))
    payments = Payment.objects.filter(status='preauth').order_by('-created')
    payments = payments.select_related('order', 'order__user')
    low_stock = get_low_stock_products()
    ctx = {'preauthorized_payments': payments, 'orders_to_ship': orders_to_ship,
           'low_stock': low_stock}
    return TemplateResponse(request, 'dashboard/index.html', ctx)


def get_low_stock_products():
    threshold = getattr(settings, 'LOW_STOCK_THRESHOLD', 10)
    products = Product.objects.annotate(total_stock=Sum('variants__stock__quantity'))
    return products.filter(Q(total_stock__lte=threshold)).distinct()

saleor/product/views.py
from __future__ import unicode_literals

from django.http import HttpResponsePermanentRedirect
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import ugettext as _

from .forms import get_form_class_for_product
from .models import Product, Category
from saleor.cart import Cart


def product_details(request, slug, product_id):
    products = Product.objects.get_available_products().select_subclasses()
    products = products.prefetch_related('categories', 'images',
                                         'variants__stock')
    product = get_object_or_404(products, id=product_id)
    if product.get_slug() != slug:
        return HttpResponsePermanentRedirect(product.get_absolute_url())
    form_class = get_form_class_for_product(product)
    cart = Cart.for_session_cart(request.cart, discounts=request.discounts)
    form = form_class(cart=cart, product=product,
                      data=request.POST or None)
    if form.is_valid():
        if form.cleaned_data['quantity']:
            msg = _('Added %(product)s to your cart.') % {
                'product': product}
            messages.success(request, msg)
        form.save()
        return redirect('product:details', slug=slug, product_id=product_id)
    template_name = 'product/details_%s.html' % (
        type(product).__name__.lower(),)
    templates = [template_name, 'product/details.html']
    return TemplateResponse(
        request, templates,
        {'product': product, 'form': form})


def category_index(request, path, category_id):
    category = get_object_or_404(Category, id=category_id)
    children_categories = category.get_children()
    breadcrumbs = category.get_ancestors(include_self=True)
    actual_path = category.get_full_path()
    if actual_path != path:
        return redirect('product:category', permanent=True, path=actual_path,
                        category_id=category_id)
    products = category.products.get_available_products().select_subclasses()
    products = products.prefetch_related('images', 'variants', 'variants__stock')
    return TemplateResponse(
        request, 'category/index.html',
        {'products': products, 'category': category,
         'children_categories': children_categories, 'breadcrumbs': breadcrumbs})

saleor/dashboard/templates/dashboard/product/attributes/confirm_delete.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Delete attribute" %} - {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--with-menu">
        <li><a href="{% url 'dashboard:product-attributes' %}">{% trans "Attributes" %}</a></li>
        <li><i class="mdi-navigation-chevron-right"></i> {% trans "Delete attribute" %}</li>
    </ul>
{% endblock %}

{% block content %}
    <p>{% trans "Are you sure you want to delete the following attribute?" %}</p>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <ul class="collection">
                <li class="collection-item">
                    {{ attribute }}
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col m6 l4 offset-m3 offset-l4 right-align">
                <a href="{% url 'dashboard:product-attributes' %}" class="btn-flat"><i class="mdi-content-clear"></i> {% trans "Cancel" %}</a>
                <button type="submit" class="btn materialize-red"><i class="mdi-action-delete"></i> {% trans "Delete" %}</button>
            </div>
        </div>
    </form>
{% endblock %}

saleor/dashboard/templates/dashboard/product/attributes/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}{% if attribute.pk %}{{ attribute }}{% else %}{% trans 'Add new attribute' %}{% endif %} - {% trans "Attributes" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-attributes{% endblock %}

{% block header_menu %}
    {% url "dashboard:product-attributes" as url %}
    {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block header_extra %}
    {% if attribute.pk %}
    <a class="dropdown-button" href="#" data-activates="attribute-delete" data-constrainwidth="false">
        <i class="mdi-navigation-more-vert"></i>
    </a>
    <ul id="attribute-delete" class="dropdown-content">
        <li>
            <a class="modal-trigger-custom" href="#base-modal"
                data-href="{% url 'dashboard:product-attribute-delete' pk=attribute.pk %}">
                {% trans "Remove attribute" %}
            </a>
        </li>
    </ul>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--with-menu">
        <li><a href="{% url 'dashboard:product-attributes' %}">{% trans "Attributes" %}</a></li>
        <li>{% if attribute.pk %}{{ attribute }}{% else %}{% trans 'Add new attribute' %}{% endif %}</li>
    </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" id="form-attributes">
        <div class="row">
            <div class="col l8">
                <div class="row">
                    {% csrf_token %}
                    {{ form.display|materializecss }}
                    {{ form.name|materializecss }}
                </div>

                <h5>{% trans "Attribute values" %}</h5>
                {{ formset.management_form }}
                {{ formset.non_form_errors.as_ul }}
                <table id="formset" class="highlight">
                    {% for form in formset.forms %}
                        {% if forloop.first %}
                            <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    <th>{{ field.label|capfirst }}</th>
                                {% endfor %}
                            </tr>
                            </thead>
                        {% endif %}
                        <tr>
                            {% for field in form.visible_fields %}
                                <td{% if forloop.last %} class="center-align"{% endif %}>
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}
                                    {{ field.errors.as_ul }}
                                    {{ field|materializecss }}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col l8 right-align">
                {% if attribute.pk %}
                    <button type="submit" class="btn">{% trans "Update" %}</button>
                {% else %}
                    <button type="submit" class="btn">{% trans "Create" %}</button>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

saleor/dashboard/templates/dashboard/product/attributes/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}

{% block title %}{% trans "Attributes" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-attributes{% endblock %}

{% block header_extra %}
    <div class="fixed-action-btn">
        <a class="btn-fab btn-floating btn-large waves-effect waves-light teal"
            href="{% url 'dashboard:product-attribute-add' %}" title="{% trans "Add attribute" %}">
            <i class="mdi-content-add"></i>
        </a>
    </div>
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs">
        <li>{% trans "Attributes" %}</li>
    </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
    <div class="row">
        <div class="col s12">
            {% if attributes %}
                <ul class="collection list list--attributes">
                    {% for attribute in attributes %}
                        <li class="collection-item list-item list--attributes-item list-item--two-lines">
                            <a class="list-item-name" href="{% url 'dashboard:product-attribute-update' pk=attribute.pk %}">{{ attribute.display }}</a>

                            <p class="list-item-desc">
                                    {% for value in attribute.values.all %}
                                    {{ value }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </p>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>{% trans "No attributes found." %}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

saleor/dashboard/templates/dashboard/product/attributes/modal_confirm_delete.html
{% load i18n %}

<form action="{% url "dashboard:product-attribute-delete" pk=attribute.pk %}" method="post">
    {% csrf_token %}
    <div class="modal-content">
        <h5>{% trans "Are you sure?" %}</h5>

        <p>
            {% blocktrans %}You are about to delete an attribute <strong>{{ attribute }}</strong>.{% endblocktrans %}
        </p>
    </div>

    <div class="modal-footer">
        <button type="submit" class="modal-action btn-flat blue-text">{% trans "Delete" %}</button>
        <a href="#!" class="modal-action modal-close btn-flat blue-text">{% trans "Cancel" %}</a>
    </div>
</form>